Task 2.1 beta
shigontsev/Epam-xt-2021 pull request #1
Opened 2021-03-17 09:44 UTC by shigontsev

2021-03-17 18:30 UTC, STeeL835 commented
First thing - instead of naming pr as "beta", you can make it a draft PR, and no one will be able to merge it without "undrafting"

2021-03-17 20:06 UTC, STeeL835 requested changes

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +        public ArraySymbol() : this("")
Better use `string.Empty`

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +        }
You could also make a ctor taking a char array instead of a method that fills created ArraySymbol from an array

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            if (arr.GetType() != this.GetType())
Are you sure you don't want a heir to be equal to an object of this class? This goes against Liskov Substitution Principle.

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            return this.ToString().CompareTo(c.ToString());
Lazy, unoptimized implementation

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            return arrChar;
Someone can use this method, get the array and change your `ArraySymbol` by changing the array (arrays are reference types)

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +        }
Usually these types of methods are static and return a *new* instance of class instead of filling existing one (for example, `TimeSpan`)

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +        }
Array has a lot of optimized methods for that

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            return new ArraySymbol(c1.ToString() + c2.ToString());
You have a method that concats arrays

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            Concat(new ArraySymbol(text));
How it's different from Concat?

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            char[] item = ToCharArray();
you can use arrChar without arrays - ToCharArray doesn't return new array, it returns the arrChar array

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            return this;
Array type has optimized methods like `Array.Copy()` and others

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            //}
Don't commit commented code

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            return c1.Equals(c2) ? false : true;
```suggestion
            return !c1.Equals(c2);
```

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.1/Program.cs
> +            Console.WriteLine(C++);
nice

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Axis.cs
> +    public class Axis
I think, you meant `Figure`, doesn't look like Axis is a parent for all figures.

By the way, as a standalone class it's more like a `Point`

---

So, if I create a list of figures, I won't be able to find perimeter or area of a figure without knowing exactly what type of figure I have?

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/IFigure.cs
> +        void Info();
Bad naming - methods should say what they do, like `PrintInfo()` or `GetInfo()` (if it returns info)

By the way, this could be achieved by making an abstract method in parent of all figures

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Circle.cs
> +            Radius = r;
I can create a Circle with negative radius, there's no incapsulation

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Circle.cs
> +        public static Circle Enter(double r, double x, double y)
* This method isn't different from constructor
* Such methods are usually named `Create..()`

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Circle.cs
> +        public double Length
I think you meant Perimeter

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Point.cs
> +        }
Logically, a point is more abstract than any figure. It can be used multiple times in figures. Therefore, I'd rather see a Point as a standalone class, which is used in `Position` property in a parent of all figures

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Line.cs
> +            => a * a;
`Math.Pow()`

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Rectangle.cs
> +            => Width * Height;
It's a property, itshouldn't start with a verb, a simple `Area` would suffice

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Rectangle.cs
> +            }
1. Logically wrong - if figure is correct, you can't create it?
2. Depending on Console in a class that doesn't need to depend on Console.

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Line.cs
> +        public Point P2;
exposing fields is a mauvais ton - make them auto-properties

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Rectangle.cs
> +        public double Height { get; private set; }
You've hidden setters on `Rectangle` to stop users from making a `Square` a rectangle with different sides?

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Circle.cs
> +        }
You could do almost the same by overriding `ToString()` - that's more common an expected pattern.

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Round.cs
> +        }
Spacing between class members is important for readability

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Round.cs
> +            => Math.PI * Radius * Radius;
This can fit on 1 line

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Triangle.cs
> +            }
You can't just return from a constructor. Constructor - is a method that initializes object after it's been created in memory. If you return now, the object will still be created and will be incorrect

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/Program.cs
> +            bool boolen = true;
boolen?

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/Input.cs
> +        }
Is empty string allowed for a name?

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/Input.cs
> +                }
`TryParse` is much better for this

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MultiUser.cs
> +    public class MultiUser
This class is more like a menu than a user (naming)

2021-03-17 20:06 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/User.cs
> +        }
User and an Editor are different entities. Remember SRP from SOLID

2021-03-18 06:18 UTC, shigontsev commented on Task_2/Task_2.1.2/Program.cs
> +            bool boolen = true;
wrong name?

2021-03-18 06:54 UTC, shigontsev commented on Task_2/Task_2.1.2/UI/User.cs
> +        }
1) the Editor is only a CommandBar and should be sent to the Menu class?
2) the user editor and the multi-user editor need to be done in two different classes MenuFigure and MenuUsers, or make global class Menu?

2021-03-18 09:35 UTC, STeeL835 commented on Task_2/Task_2.1.2/Program.cs
> +            bool boolen = true;
yes, this name doesn't mean anything (+ I guess, there's a typo

2021-03-18 09:35 UTC, STeeL835 commented on Task_2/Task_2.1.2/Program.cs
> +            bool boolen = true;
> wrong name?

Yes, this name doesn't mean anything (+ I guess, there's a typo

2021-03-19 06:04 UTC, shigontsev commented
Task 2.1.1 fixing finished

2021-03-19 11:06 UTC, shigontsev commented
Task 2.1.2 is temporarily located in the "Task_2.1.2" branch for fix

2021-03-31 20:58 UTC, STeeL835 reviewed
The code is clean and almost correct. Logic is correctly divided into classes
But incapsulation with holes and commented code - is something that can be improved

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +        }
You can resolve this now

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +            return this.arrChar.Equals(obj as ArraySymbol);
* You call Equals of array, which compares only references, not elements.
* You should've called `Equals(ArraySymbol)` anyway

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +                return 1;
if arr1 > arr2 result should be greater than 0, if arr1 < arr2, result should be less than zero. Here `[1,2] > [1,2,3]` and `[1,2,3] > [1,2]` (both >), which is wrong

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/MyDLL/ArraySymbol.cs
> +        }
There are a lot of Concat overloads, you could make this main implementation with params too, since there are overloads with params. To create new array only once

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Circle.cs
> +    public class Circle:Figure
Usually dev put spaces around colon here

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Circle.cs
> +                    value = 1;
What's the point?

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Circle.cs
> +                //{ throw new ArgumentException(" Wrong! "); }
Commented code

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Circle.cs
> +            }
What if I put 0 radius?

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Circle.cs
> +                "Длина = " + Length);
```suggestion
            return string.Join(Environment.NewLine, "Фигура: Окружность",
                "Центр = " + Position,
                "Радиус = " + Radius,
                "Длина = " + Length);
```

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Figure.cs
> +        }
* Why not allow to pass a Point straight away? That would be easier and it's Point's job (and changes in Point would not require changes in Figure classes). So, why duplicate this logic?
* Commented code

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/IFigure.cs
> +    }
Figures should be busy being figures (thats their Single Responcibility Principle of SOLID). If someone wants to print data from ToString to console, custom terminal, to Debug.WriteLine, to logs or somewhere else - that should be their job, not figures'.

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Line.cs
> +            Position = p1; SecondPosition = p2;
We usually don't put 2 lines on one - that's an unusual pattern and slows down code scanning (when you look for something. The exception is - table-like aligning that **helps** with that (when there are a lot of similar lines, difference between which is hard to find).

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Rectangle.cs
> +        public double Height { get; set; }
Negative values? Wouldn't that be an incorrect rectangle with negative sides? (incapsulation)

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Rectangle.cs
> +        }
You don't validate values here, but you should - class should protect objects from being in incorrect state. It's okay (and the way) to throw exceptions here, if data is incorrect.

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Rectangle.cs
> +        }
Here you depend on Console, but what if environment doesn't have it? Or it's a server-side application? Figures should be figures, user input is another job that is best handled by others (they know how) (SRP)

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Round.cs
> +    public class Round : Circle
Why Circle can't do the same as Round? I think you could implement all of this in one class instead of 2

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Entity/Square.cs
> +        }
I can create a Square and with the help of inherited Width and Height properties make it a Square with different sides, and voila - object is broken.

Here I'd suggest to have only Rectangle class, but implement a member that would allow to know whether this rectangle is a square or not (since square is a case of rectangle), `IsSquare` property for example + another ctor from Square

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/Program.cs
> +                multiUser.CommandBar(ref exit);
you could use return value instead of ref parameter

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/Input.cs
> +                string enter = Console.ReadLine().Trim();
that's super cool that you used Trim

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/Input.cs
> +        }
You can resolve this now

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/Input.cs
> +        }
You could make this more universal by allowing to pass a hint string to EnterDouble. Would make it easier to show a different hint.

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/Input.cs
> +        }
We don't use underscores in names (except for unit test names - they are long). Here it `EnterPositiveDouble` would fit better

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/Input.cs
> +            } while (true);
"but what is wrong, why does it say 'enter value' when I just did that?" Good UI tells what's wrong or at least what is a correct value.

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MainMenu.cs
> +        }
* What if user already exists
* Plus, better not use such things as Last - this collection can change between adding and printing text (multithreading). Clean Code would be creating a variable for created user and using it in both places.

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MainMenu.cs
> +            }
You iterate through list to iterate through list again in every outer iteration to find an index. That's O(n^2), when it could be O(n) - just do it with `for` loop.
Plus it would show same index 2 times if list contains 2 users with same name

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MainMenu.cs
> +            return Users.ElementAt(index);
List has an indexer that returns value fast. LINQ method doesn't use it and has to go through items one by one before it finds something.

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MainMenu.cs
> +            }
Generic exception. If code fails because of OutOfMemoryException for example, the user will see an error about index, which would be a lie.

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MainMenu.cs
> +                }
while exit - keep going, don't exit
logic is flawed, call the variable `exitNotRequired`, that would not be confusing

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MenuFigures.cs
> +        }
You could save here the whole user, why only figures (if task says that app calls user by name)

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MenuFigures.cs
> +                    Console.WriteLine("Выбрана фигура " + type);
Repeating piece of code (or at least string) - could move into method (or constant)

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MenuFigures.cs
> +                //Figures.Add(Line.Enter(Input.X(), Input.Y(), Input.X(), Input.Y())); ShowLastFigure(); break;
Commented code

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/MenuFigures.cs
> +                    AddFigure(Ring.CreateFigure(Input.InnerR(), Input.OuterR(), Input.X(), Input.Y())); break;
if inner R is bigger than outer R - that's not validated neither here nor in entity

2021-03-31 20:58 UTC, STeeL835 commented on Task_2/Task_2.1.2/UI/User.cs
> +        public List<Figure> Figures;
```suggestion
        public List<Figure> Figures { get; private set; }
```
Just so someone can't replace a reference to another list

2021-05-17 08:44 UTC, shigontsev commented
1) completely fixed Task 2.1.1,
2) minimal fixed Task 2.1.2, I hate myself for that =(

2021-07-18 04:57 UTC, merged